version: "3.3"

services:
  broker:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672:5672

  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: microservices
      POSTGRES_USER: postgres
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/init.sql

  tracing:
    image: openzipkin/zipkin
    ports:
    - 9411:9411